### ISSUE TITLE
Clover Bootloader menu not loaded by RefindPlus

### ISSUE THREAD

**Issue by jzrodriguez98** [dakanji/RefindPlus#21] opened 2021-02-05 18:40 UTC
I was trying to use RefindPlus to chainload OpenCore and Windows 10, and also have a boot menu entry for Clover EFI boot loader which is installed in another drive EFI. RefindPlus was successfully loading the Clover boot loader until very recently, when I installed an update of Clover and for some reason after applying the update, RefindPlus stopped loading successfully Clover boot menu. I have not done anything else other than updating Clover files to v5129 and OpenCore files to v0.6.6. Do you know if I need to change something else in the refind.config file to fix this?

**Comment by dakanji** [comment] 2021-02-05 19:11
Please provide the information requested in the issue template.

**Comment by jzrodriguez98** [comment] 2021-02-05 19:44
**Describe the bug**
I was trying to use RefindPlus to chainload OpenCore and Windows 10, and also have a boot menu entry for Clover EFI boot loader which is installed in another drive EFI. RefindPlus was successfully loading the Clover boot loader until very recently, when I installed an update of Clover and for some reason after applying the update, RefindPlus stopped loading successfully Clover boot menu. I have not done anything else other than updating Clover files to v5129 and OpenCore files to v0.6.6. 

**To Reproduce**
Steps to reproduce the behaviour:
1. Installed Refind files in the EFI partition created in the SSD where I have installed macOS Big Sur.
2. Copied RefindPlus_x64-REL.efi to \EFI\BOOT folder and renamed it as BOOTx64.efi
3. Configured refind.conf listing the boot options as follows:

menuentry "Windows 10 Pro" {
	volume 4F88EC2B-4C2F-484A-A136-DEA325EB9CF0
	loader \EFI\Microsoft\Boot\bootmgfw.efi
}

menuentry "OpenCore" {
    loader \EFI\OC\OpenCore.efi
}

menuentry "Clover" {
	volume 6EB47F8D-10CB-4CAA-9589-ED6259F814AF
	loader \EFI\CLOVER\Cloverx64.efi
}


scanfor manual
4. When rebooting, select Clover from the boot entries. Nothing happens except for seeing the screen flashing or seeing a blank screen with a message stating "Paused - press any key to continue", and when I press any key, it goes back to the refindplus boot screen. The problem only occurs with Clover, since OpenCore is booting without any issues.

**Expected behaviour**
When you select Clover from the boot entries, you are supposed to see the Clover boot loader menu screen with the boot entries.
[BOOT.zip](https://github.com/dakanji/RefindPlus/files/5934834/BOOT.zip)


**Environment:**
 - RefindPlus Version : [e.g. v0.12.0.AN]
 - Hardware
   * Computer         : Hackintosh GA-Z97-HD3 v2.1, Intel i5 4690k
   * GPU Model        : Gigabyte RX 580
   * GPU Port         : DVI-I, HDMI (DP not in use)
   * GPU Flash        : NO
 - Affected OS        : Mac OS Big Sur v11.2 (20D64)

**Log and Config Files**
I attached a zip file containing the refind files I have copied to my EFI Boot folder. 

**Additional context**
Add any other context about the problem here.

**Comment by dakanji** [comment] 2021-02-05 19:49
Thanks. Can you edit your post to include the RefindPlus Version? 
This is perhaps the most important piece of information.

**Comment by dakanji** [comment] 2021-02-05 20:06
You are running an outdated version of RefindPlus.
Update to the current version.

**Comment by jzrodriguez98** [comment] 2021-02-05 20:08
I tried to use the most recent version but it did not work (it's not progressing from a blank screen appearing right after the Gigabyte logo). That's why I kept using the previous version.

**Comment by dakanji** [comment] 2021-02-05 20:16
> I tried to use the most recent version

What version exactly?

**Comment by jzrodriguez98** [comment] 2021-02-05 20:16
The RefindPlus_x64-001200_AQ version

**Comment by jzrodriguez98** [comment] 2021-02-05 20:17
Could you please advise what could be happening?

**Comment by dakanji** [comment] 2021-02-05 20:18
OK. Provide logs for v001200_AQ indicating the blank screen issue and the logs from v001200_AM with the Clover issue (the ones you attached show booting into OpenCore which you have said is fine.

**Comment by jzrodriguez98** [comment] 2021-02-05 20:21
I'll see if I'm able to obtain some logs. When I tried to debug version, it was not progressing from a black screen and I had to press the reboot button in the PC.

**Comment by dakanji** [comment] 2021-02-05 20:23
Logs are produced either way. May be incomplete but till present and gives information.

**Comment by jzrodriguez98** [comment] 2021-02-05 20:26
I'm rebooting to get back to you.

**Comment by jzrodriguez98** [comment] 2021-02-05 20:41
[21d05v3322.log](https://github.com/dakanji/RefindPlus/files/5935178/21d05v3322.log)
I booted using DEBUG version v001200_AQ. Attached is the log and screenshot where you can see what happens when I boot using the latest release version.


![Refindplus Debug AQ version screenshots ](https://user-images.githubusercontent.com/10348976/107086709-c459a580-67d0-11eb-9b84-bb527af07884.jpg)

**Comment by jzrodriguez98** [comment] 2021-02-05 20:42
I'm going to rename the refind.conf to config.conf and reboot to see what happens

**Comment by jzrodriguez98** [comment] 2021-02-05 20:50
![New Refindplus debug picture](https://user-images.githubusercontent.com/10348976/107087462-dd168b00-67d1-11eb-96b0-1f55de53d987.jpg)
[21d05v4428.log](https://github.com/dakanji/RefindPlus/files/5935259/21d05v4428.log)
[BOOT.zip](https://github.com/dakanji/RefindPlus/files/5935268/BOOT.zip)
[21d05v4338.log](https://github.com/dakanji/RefindPlus/files/5935273/21d05v4338.log)
I rebooted again with debug version v001200_AQ and file config.conf. Attached are the log files and the refind files I'm using.

**Comment by dakanji** [comment] 2021-02-05 20:51
Try Version 0.12.0.AN

**Comment by jzrodriguez98** [comment] 2021-02-05 20:54
About the config.conf, do I need to change something? Did you review the boot entries I included there?

**Comment by jzrodriguez98** [comment] 2021-02-05 21:02
I rebooted using debug version 0.12.0.AN and I was able to see the refindplus boot screen with all entries. Here is the result (logs and screenshot of Clover error when I selected it from refindplus boot screen entries.).
![Clover error](https://user-images.githubusercontent.com/10348976/107088681-b6f1ea80-67d3-11eb-83a2-2bbc5f30aae3.jpg)
[21d05v5621.log](https://github.com/dakanji/RefindPlus/files/5935321/21d05v5621.log)
[21d05v5653.log](https://github.com/dakanji/RefindPlus/files/5935323/21d05v5653.log)

**Comment by dakanji** [comment] 2021-02-05 21:11
OK.

seems there are two issues overlapping:
1. Something wrong with RefindPlus AQ
2. Something wrong or changed with Clover

There is nothing you can change in your config to resolve the RefindPlus issue and I will work to fix it. 

Suggest you roll back to working version of Clover and stick with v0.12.0.AN until a new version of RefindPlus is released.

**Comment by startergo** [comment] 2021-02-05 21:29
So this PC gets stuck at the same spot as the MBP with the AQ and 430 firmware and AN works on both.

**Comment by jzrodriguez98** [comment] 2021-02-05 21:43
> OK.
> 
> seems there are two issues overlapping:
> 
> 1. Something wrong with RefindPlus AQ
> 2. Something wrong or changed with Clover
> 
> There is nothing you can change in your config to resolve the RefindPlus issue and I will work to fix it.
> 
> Suggest you roll back to working version of Clover and stick with v0.12.0.AN until a new version of RefindPlus is released.

I will do that for now and keep monitoring this.

**Comment by dakanji** [comment] 2021-02-06 11:16
@jzrodriguez98 

Please test the 'Problem" Clover version on upstream rEFInd 0.12.0 to see whether it loads without issue?

**Comment by jzrodriguez98** [comment] 2021-02-06 13:12
Thanks a lot. I will do that later today.

**Comment by jzrodriguez98** [comment] 2021-02-06 20:18
What is the command to download the upstream version of this repo?

**Comment by dakanji** [comment] 2021-02-06 20:28
This is the main RefindPlus repo. There is no upstream version. What are you trying to achieve?

To do the requested test, install rEFInd as you did before, do not swap in the RefindPlus efi or config and boot with that to see.

**Comment by dakanji** [comment] 2021-02-07 07:52
RefindPlus related issues have been addressed in the codebase.
Please confirm the outcome of the the test of Clover on rEFInd.

**Comment by jzrodriguez98** [comment] 2021-02-07 12:37
Sorry, I meant how to obtain the upstream rEFInd 0.12.0. I downloaded refind files from https://sourceforge.net/projects/refind/

**Comment by dakanji** [comment] 2021-02-07 13:28
Previously, you installed rEFInd and then swapped in the RefindPlus efi.  Well, just do the same thing and do not swap in the RefindPlus efi this time.

Easier still, since you already have a RefindPlus setup, rename the RefindPlus efi temporarily as something else and put in a rEFInd efi file.

**Comment by startergo** [comment] 2021-02-07 13:37
I can confirm MBP firmware 430 works with latest commit

**Comment by jzrodriguez98** [comment] 2021-02-07 14:56
> Previously, you installed rEFInd and then swapped in the RefindPlus efi.  Well, just do the same thing and do not swap in the RefindPlus efi this time.
> 
> 
> 
> Easier still, since you already have a RefindPlus setup, rename the RefindPlus efi temporarily as something else and put in a rEFInd efi file.

I did what you suggest and it did not work.

**Comment by dakanji** [comment] 2021-02-07 14:59
You need to give more detail when reporting issues.
Did you mean Clover did not work or rEFInd did not in the first place?
What exactly happened?

As for latest commit, sure you can build and try but still trying to understand the Clover angle.

**Comment by jzrodriguez98** [comment] 2021-02-07 15:51
I used the refind.efi (renaming it) that can be found in the refind files I previously downloaded as you suggested and I got an error similar to the one I got with refindplus.efi. Definitely it's a cloverx64 problem that is beyond me. I'll have to report it in a clover forum.

**Comment by jzrodriguez98** [comment] 2021-02-07 16:04
I built refind from latest commit and while the memory issue is gone, obviously it's still having the same issue with loading the clover boot screen (an issue with loading cloverx64.efi).

**Comment by dakanji** [comment] 2021-02-07 16:59
Thanks.

Seems to be Clover related if manifesting in rEFInd and best to flag with the developers as you said

Will close this now. Thanks for helping out.

**Closed by dakanji** 2021-02-07 16:59 UTC
Labels: Bug

**Comment by jzrodriguez98** [comment] 2021-02-07 17:32
@Sergey (slice) is replying in the issue I reported at clover repo that it's a refind problem. I guess he meant that since the clover developers continued changing clover to make it work better and better with macOS Big Sur, refind has to be updated in line with what's new in Clover.

**Comment by dakanji** [comment] 2021-02-07 17:37
Just paste a link to this issue in the issue you raised there thanks.
