### ISSUE TITLE
Manual Stanza Handling Issues

### ISSUE THREAD

**Issue by billabongbruno** [dakanji/RefindPlus#57] opened 2021-06-09 16:28 UTC
**Describe the Bug:**
RELEASE Version does NOT load any entry if any .efi drivers are present in the drivers_x64 folder.
Same as described in **Aditional Context** section on the already closed issue https://github.com/dakanji/RefindPlus/issues/49

**To Reproduce:**

1. Boot up RefindPlus
2. Screen shows as blank / black / grey (depending on themes applied or not), no icons are shown

**Expected Behaviour:**
RefindPlus would load without throwing any error message.

**Environment:**

 - RefindPlus Version : [v0.13.2.AE] - RELEASE version
 - Hardware
   * Computer         : [Microsoft Surface Pro 4]
   * Motherboard      : [Microsoft]
 - Affected OS        : [ALL - None are shown]

**Additional Context:**
Workaround provided in https://github.com/dakanji/RefindPlus/issues/49#issuecomment-845027198 does not work anymore.

**Comment by dakanji** [comment] 2021-06-09 16:36
RELEASE Version does NOT load any entry if any .efi drivers are present in the drivers_x64 folder.

Do this mean DEBUG version does?

If not, please provide a log file

**Comment by billabongbruno** [comment] 2021-06-09 16:50
> > RELEASE Version does NOT load any entry if any .efi drivers are present in the drivers_x64 folder.
> 
> Does this mean DEBUG version does not have the same issue?
> 
> If it also does, please provide a log file
> 
> EDIT
> Provide your config file in either case
> Thanks

No, for the time being it meant that I had only tried the RELEASE version.
I'm gonna try the DEBUG one now and produce a log file.

**Comment by dakanji** [comment] 2021-06-09 17:06
OK. Please always run the Debug version in order so as to be able to provide a log as per the issue template as cannot do much without this.

Also provide your config file as may be relevant.

**Comment by billabongbruno** [comment] 2021-06-09 17:08
> > RELEASE Version does NOT load any entry if any .efi drivers are present in the drivers_x64 folder.
> 
> Does this mean DEBUG version does not have the same issue?
> 
> If it also does, please provide a log file
> 
> EDIT
> Provide your config file in either case
> Thanks

Confirmed.
DEBUG shows same behaviour.

Attached are the .log and my .conf files (config.conf is zipped, because of GitHub upload limitations).

[21k09t0008.log](https://github.com/dakanji/RefindPlus/files/6625591/21k09t0008.log)

[config.zip](https://github.com/dakanji/RefindPlus/files/6625602/config.zip)

**Comment by dakanji** [comment] 2021-06-09 19:40
Thanks.

Yet more logging in X132
[X132-BOOTx64.zip](https://github.com/dakanji/RefindPlus/files/6626453/X132-BOOTx64.zip)

**Comment by billabongbruno** [comment] 2021-06-09 20:21
> Thanks.
> 
> Yet more logging in X132
> [X132-BOOTx64.zip](https://github.com/dakanji/RefindPlus/files/6626453/X132-BOOTx64.zip)

[21k09w1844.log](https://github.com/dakanji/RefindPlus/files/6626676/21k09w1844.log)

Here you go.

**Comment by dakanji** [comment] 2021-06-09 20:37
Have a go with X133. This includes an attempted fix
[X133-BOOTx64.zip](https://github.com/dakanji/RefindPlus/files/6626765/X133-BOOTx64.zip)

**Comment by billabongbruno** [comment] 2021-06-09 20:45
> Have a go with X133. This includes an attempted fix
> [X133-BOOTx64.zip](https://github.com/dakanji/RefindPlus/files/6626765/X133-BOOTx64.zip)

No luck.
Halts on black screen too.

Here is the log file:
[21k09w4205.log](https://github.com/dakanji/RefindPlus/files/6626800/21k09w4205.log)

**Comment by dakanji** [comment] 2021-06-09 21:13
Cheers. Please try X134:
[X134-BOOTx64.zip](https://github.com/dakanji/RefindPlus/files/6626916/X134-BOOTx64.zip)

**Comment by billabongbruno** [comment] 2021-06-09 21:22
> Cheers. Please try X134:
> [X134-BOOTx64.zip](https://github.com/dakanji/RefindPlus/files/6626916/X134-BOOTx64.zip)

Again, no luck.
[21k09x1711.log](https://github.com/dakanji/RefindPlus/files/6626954/21k09x1711.log)

**Comment by dakanji** [comment] 2021-06-09 21:31
its ok. I already know what the issue is and can fix but trying to get to the exact where and why.

Please try X135 (Doesn't contain a fix)
[X135-BOOTx64.zip](https://github.com/dakanji/RefindPlus/files/6626983/X135-BOOTx64.zip)

**Comment by billabongbruno** [comment] 2021-06-09 21:38
> its ok. I already know what the issue is and can fix but trying to get to the exact where and why.
> 
> Please try X135 (Doesn't contain a fix)
> [X135-BOOTx64.zip](https://github.com/dakanji/RefindPlus/files/6626983/X135-BOOTx64.zip)

Oh, apologies.
I just assumed you were implementing different fixes with every new version you sent me.

This issue had been addressed and fixed before, so I assume some of the commits got reverted or something else broke it.

Anyway, here is the log file:
[21k09x3518.log](https://github.com/dakanji/RefindPlus/files/6627022/21k09x3518.log)

**Comment by dakanji** [comment] 2021-06-09 21:53
Thanks. Some do have fix attempts.
Anyway, thanks to the last log, I have found what the "where" but not yet sure of the "why".
I could "fix" it immediately but could not be addressing the root cause and need to ask for some insight

@joevt ... can you help cast an eye?
Basically looks like this line... 
https://github.com/dakanji/RefindPlus/blob/9641ab091c8c6e3d8a35df63f0f5fbb3b50b4425/BootMaster/config.c#L1285
...is somehow unsetting the `Entry->Enabled` flag.
Since the While loop has Entry->Enabled as an inner condition, the rest of the entry is failing. Problematically, the whole process is crashing later. Looks like some sort of memory allocation issue but it is not immediately apparent to me where this is springing from. Any clues?

**Comment by billabongbruno** [comment] 2021-06-09 21:55
> Thanks. Some do have fix attempts.
> Anyway, thanks to the last log, I have found what the "where" but not yet sure of the "why".
> I could "fix" it immediately but could not be addressing the root cause and need to ask for some insight
> 
> @joevt ... can you help cast an eye?
> Basically looks like this poolprint...
> https://github.com/dakanji/RefindPlus/blob/9641ab091c8c6e3d8a35df63f0f5fbb3b50b4425/BootMaster/config.c#L1285-L1288
> 
> 
> ...is somehow unsetting the `Entry->Enabled` flag.
> Since the While loop has Entry->Enabled as an inner condition, the rest of the entry is failing. Problematically, the whole process is crashing later. Looks like some sort of memory allocation issue but it is not immediately apparent to me where this is springing from. Any clues?

No rush.
I am not in this for the quick fix.

Take your time to debug and let me know if I can be of further use.

**Comment by dakanji** [comment] 2021-06-09 22:10
Thanks for the help.
Can you try X136?

[X136-BOOTx64.zip](https://github.com/dakanji/RefindPlus/files/6627140/X136-BOOTx64.zip)

**Comment by billabongbruno** [comment] 2021-06-09 22:39
> Thanks for the help.
> Can you try X136?
> 
> [X136-BOOTx64.zip](https://github.com/dakanji/RefindPlus/files/6627140/X136-BOOTx64.zip)

Ok, so.
A few things happened.

1 - This one works.
2 - It's takes a long time to load (expected, it's a DEBUG version).
3 - I booted without a theme into every OS (Ubuntu 20.04, ChromeOS - Brunch Framework, Windows 10 and MacOS BigSur 11.4) and everything worked.
4 - I tried hiding entries and it worked while the theme was disabled.
5 - All the previously hidden entries (while the theme was commented out) reappeared after re-editing the config.conf to uncomment the theme line out, which tells me RefindPlus is not saving its configurations after a minor edit to the config.conf (unsure if it's a bug or a feature, being a DEBUG version and all).

I am attaching only the last log file with a successful boot into Ubuntu, from where I'm writing this right now.

[21k09y3248.log](https://github.com/dakanji/RefindPlus/files/6627243/21k09y3248.log)

**Comment by dakanji** [comment] 2021-06-09 22:51
>  5 - All the previously hidden entries (while the theme was commented out) reappeared after re-editing the config.conf to uncomment the theme line out

Will take a look at this later.
Can you try X137 in the meantime?

[X137-BOOTx64.zip](https://github.com/dakanji/RefindPlus/files/6627283/X137-BOOTx64.zip)

**Comment by billabongbruno** [comment] 2021-06-09 23:08
> > 5 - All the previously hidden entries (while the theme was commented out) reappeared after re-editing the config.conf to uncomment the theme line out
> 
> Will take a look at this later.
> Can you try X137 in the meantime?
> 
> [X137-BOOTx64.zip](https://github.com/dakanji/RefindPlus/files/6627283/X137-BOOTx64.zip)

1 - X137 does not work, hangs on blank screen
2 - X136 worked, but I noted something else: None of the "dont_scan" worked. All entries was visible all the time.

[21k09z0244.log](https://github.com/dakanji/RefindPlus/files/6627341/21k09z0244.log)

**Comment by dakanji** [comment] 2021-06-09 23:34
Thanks ... Will pick up on the other items later.

Can you try X138?

[X138-BOOTx64.zip](https://github.com/dakanji/RefindPlus/files/6627423/X138-BOOTx64.zip)

**Comment by billabongbruno** [comment] 2021-06-10 00:03
> Thanks ... Will pick up on the other items later.
> 
> Can you try X138?
> 
> [X138-BOOTx64.zip](https://github.com/dakanji/RefindPlus/files/6627423/X138-BOOTx64.zip)

Does not boot, but here is the log file:
[21k09z5609.log](https://github.com/dakanji/RefindPlus/files/6627504/21k09z5609.log)

**Comment by dakanji** [comment] 2021-06-10 00:37
Thanks ... Will study the outputs and get back tomorrow.

**Comment by billabongbruno** [comment] 2021-06-10 00:39
> Thanks ... Will study the outputs and get back tomorrow.

No worries.

I should also be in bed by now, it's 01:39 am here.

Thanks for the help.
See you tomorrow.

**Comment by dakanji** [comment] 2021-06-10 08:22
Please give these two a try when you have a min
[X139-X140_Archive.zip](https://github.com/dakanji/RefindPlus/files/6629592/X139-X140_Archive.zip)

**Comment by billabongbruno** [comment] 2021-06-10 12:02
> Please give these two a try when you have a min
> [X139-X140_Archive.zip](https://github.com/dakanji/RefindPlus/files/6629592/X139-X140_Archive.zip)

Here you go, with all the variants:
[X140_Without_Theme.log](https://github.com/dakanji/RefindPlus/files/6631189/X140_Without_Theme.log)
[X140_With_Theme.log](https://github.com/dakanji/RefindPlus/files/6631190/X140_With_Theme.log)
[X139_With_Theme.log](https://github.com/dakanji/RefindPlus/files/6631191/X139_With_Theme.log)
[X139_Without_Theme.log](https://github.com/dakanji/RefindPlus/files/6631193/X139_Without_Theme.log)

**Comment by dakanji** [comment] 2021-06-10 12:44
Thanks. Will close the issue with a commit presently and issue a new release.

> X139 themed continues to display all entries, even the previously deleted ones.

Could be that some thing is misconfigured in the theme config file.
Share the file

**Comment by billabongbruno** [comment] 2021-06-10 13:41
> Thanks. Will close the issue with a commit presently and issue a new release.
> 
> > X139 themed continues to display all entries, even the previously deleted ones.
> 
> Could be that some thing is misconfigured in the theme config file.
> Share the file

I don't think it is.
It works fine with rEFInd and with the other version that you sent me (in issue #49 )

Regardless, here it is:

[theme.zip](https://github.com/dakanji/RefindPlus/files/6631807/theme.zip)

**Comment by dakanji** [comment] 2021-06-10 14:17
> It works fine with rEFInd and with the other version that you sent me

There is a kind of bug in both of those that is fixed here although it has been present for so long that it might be that it can't be changed any more and must now be considered a feature.
 
You should need to add `hidden_tags` to your `showtools` line to be able to manage hidden tags but it works without this in rEFInd and has done for ages.

I might just go with the flow on this and revert the fix.

**Closed** 2021-06-10 16:06 UTC
Labels: Bug

**Comment by billabongbruno** [comment] 2021-06-11 23:44
> > It works fine with rEFInd and with the other version that you sent me
> 
> There is a kind of bug in both of those that is fixed here although it has been present for so long that it might be that it can't be changed any more and must now be considered a feature.
> 
> You should need to add `hidden_tags` to your `showtools` line to be able to manage hidden tags but it works without this in rEFInd and has done for ages. Without adding this, when you hide something, you can't set it back not to be hidden.
> 
> I might just go with the flow on this and revert the fix.
> 
> EDIT.
> Decided to revert the fix to stay consistent with rEFInd

Oh, I see.
I had no idea, sorry.

Glad you knew exactly what was going on.

**Comment by billabongbruno** [comment] 2021-06-11 23:44
> New release issued ... Thanks for raising the issue and helping debug.

No problem.
As soon as I get the chance, I'll try out the new version as well and report back should any issues arise.

Best regards,
Bruno.

**Comment by billabongbruno** [comment] 2021-06-13 15:26
> New release issued ... Thanks for raising the issue and helping debug.

Hey there.

As promised, I gave it a shot.
A very thorough and extensive shot.

I have to stay, SUPERB work.

Everything works as it should and HiddenTags are stored in the drive itself, not NVRAM, thus preventing excessive weardown of it.

No issues whatsoever that I could pick up on.

In fact, the loading time itself is incredible.
From the moment I choose whatever OS I want, RefindPlus instantly loads it (I'm using "graphics on" for every stanza) and does not have like a 3 second timeout as rEFInd did, which makes RefindPlus even better.

Blazing fast.

Tremendous work.

Have a great upcoming week.

Many thanks, fellow @dakanji .

Bruno Santana.
