### ISSUE TITLE
Various Errors with Manual Stanzas

### ISSUE THREAD

**Issue by billabongbruno** [dakanji/RefindPlus#49] opened 2021-05-20 10:34 UTC
**Describe the Bug:**
When loading manual boot stanzas for any Linux Distro (tested Ubuntu 20.04 and Linux Mint 20.1) pointing to vmlinuz and initrd.

**To Reproduce:**
1. Boot up RefindPlus
2. Choose my manually entered Linux Distro entry.
3. RefindPlus throws following message: RefindPlus - Booting OS --> Starting vmlinuz-5.4.0.73-generic --> Using load options (....) ---> Error: Load Error while loading vmlinuz-5.4.0.73-generic --> *Paused: Press Any Key to Continue*

**Expected Behaviour:**
After choosing the manually added entry to any of the Linux Distros, RefindPlus would load without throwing any error message.

**Environment:**
 - RefindPlus Version : [v0.13.2.AD]
 - Hardware
   * Computer         : [ACER Nitro 5 AN-515-52]
   * Motherboard      : [ACER]
 - Affected OS        : [Linux Distro --> Ubuntu 20.04 and Linux Mint 20.1]

**Additional Context:**

**Unaware if it's a bug and / or related, but the DEBUG Version does not show ANY entry at all.
Also, RELEASE Version does NOT load any entry if any .efi drivers are present in the drivers_x64 folder.**
**EDIT: Dev provided workaround for these two issues: https://github.com/dakanji/RefindPlus/issues/49#issuecomment-845027198**

Manual boot stanzas work correctly in "main" version of rEFInd.
Entries regarding the Linux Distros are as follows:

menuentry "Linux Mint 20.1" {
    graphics on
    icon     /EFI/refindPlus/themes/refind-black/icons/os_linuxmint.png
    volume   8804259d-cd36-4a0b-9afc-e0429e3b7319
    loader   /boot/vmlinuz-5.4.0-73-generic
    initrd   /boot/initrd.img-5.4.0-73-generic
    options  "ro root=UUID=196cb73c-2f3f-4a32-8a37-85051fe93225 ro fsck.mode=skip quiet splash"
}

menuentry "Ubuntu 20.04" {
    graphics on
    icon     /EFI/refindPlus/themes/refind-black/icons/os_ubuntu.png
    volume   91240980-28cd-4c2a-ae18-950fc40d5143
    loader   /boot/vmlinuz-5.8.0-53-generic
    initrd   /boot/initrd.img-5.8.0-53-generic
    options  "ro root=UUID=ec62f342-0947-4392-bade-0aa7005a6867 ro fsck.mode=skip quiet splash $vt_handoff"
}

**Log Files**
Log file attached, as well as config.conf (zipped).
[Bruno_21j20k0953.log](https://github.com/dakanji/RefindPlus/files/6515097/Bruno_21j20k0953.log)
[config.zip](https://github.com/dakanji/RefindPlus/files/6515103/config.zip)

**Comment by dakanji** [comment] 2021-05-20 10:42
Thanks.

It looks like it is crashing when trying to scan the manual stanzas
Can you set the `log_level` config token to 4 and regenerate the log?

**Comment by billabongbruno** [comment] 2021-05-20 10:47
You're most welcome.

I most certainly can, I just need like 30 minutes because I will be on the move.

Will upload ASAP.

Best regards,
Bruno.


________________________________

**Comment by billabongbruno** [comment] 2021-05-20 11:34
> Thanks.
> 
> It looks like it is crashing when trying to scan the manual stanzas
> Can you set the `log_level` config token to 4 and regenerate the log?

Here is the log with log_level token set to 4, as per your recommendation:

[21j20m2811.log](https://github.com/dakanji/RefindPlus/files/6515519/21j20m2811.log)

**Comment by billabongbruno** [comment] 2021-05-20 11:40
EDIT:
Here is the log with uncommmented log_level token.

(With theme active)

Will upload one without the theme right after.
[Uncommented_Active_Theme_21j20m3618.log](https://github.com/dakanji/RefindPlus/files/6515544/Uncommented_Active_Theme_21j20m3618.log)

**Comment by billabongbruno** [comment] 2021-05-20 11:45
EDIT2:
Here is the log with uncommented log_level token (set to 4) and with the custom theme disabled.

[Uncommented_Disabled_heme_21j20m4126.log](https://github.com/dakanji/RefindPlus/files/6515570/Uncommented_Disabled_heme_21j20m4126.log)

**Comment by dakanji** [comment] 2021-05-20 11:54
There is a bug in `firmware_bootnum`  feature.

Pending a fix, you you should be able to bypass this by removing the `Mac OS via BootNext` stanza which has this.
Probably better to just remove all the disabled stanzas.

Please rerun and share the log after this to confirm that is the only issue there.

Thanks

**Comment by billabongbruno** [comment] 2021-05-20 12:50
And the log with log_level token uncommented:

[Uncommentend_log_level_4_Theme_Enabled_21j20n4756.log](https://github.com/dakanji/RefindPlus/files/6515998/Uncommentend_log_level_4_Theme_Enabled_21j20n4756.log)

**Comment by billabongbruno** [comment] 2021-05-20 12:51
I'm far from being an expert, but I'm assuming RefindPlus is expecting to find a .efi file rather than a kernel being loaded.

Or am I miles off?

**Comment by dakanji** [comment] 2021-05-20 15:04
Will take a look later thanks.

**Comment by dakanji** [comment] 2021-05-21 04:42
> I miles off?

No. You are warm on that.

I think I have spotted the change that is causing the issue but to be sure, can you run rEFInd and try to load one of those stanzas? 

Set the rEFInd log_level token to 4 and share the log please.

**Comment by billabongbruno** [comment] 2021-05-21 16:18
> > I miles off?
> 
> No. You are warm on that.
> 
> I think I have spotted the change that is causing the issue but to be sure, can you run rEFInd and try to load one of those stanzas?
> 
> Set the rEFInd log_level token to 4 and share the log please.

Hey there.

So, I have been trying my best to do that, but rEFInd just doesn't print out a log file anywhere.
I am unsure that it logs anything when installed in a Windows-based machine.
I read somewhere that the logging occurs only on Mac-based machines.

I've tried both commented and uncommented log_level 4 token.

No log file is produced anywhere.

=/

**Comment by dakanji** [comment] 2021-05-22 04:03
>No log file is produced anywhere.

I see. Not sure exactly of the details but would have expected it work to.
Might be worth raising that as an issue to the rEFInd project.

Will see about the refindPlus issues later.

PS: To activate a token, you need to have it not commented and there is no need to experiment between commenting or not.
The RefindPlus one works in a specific way in that the debug build always produces a log and therefore, if commented, there will still be one (at level 0). Look at the ReadMe file and the accompanying text in the config file to understand.

**Comment by dakanji** [comment] 2021-05-23 17:25
Hello,

Just realised you are not loading any drivers ... can you retry with an ext4 driver?
This would typically be needed

**Comment by billabongbruno** [comment] 2021-05-23 17:28
> > No log file is produced anywhere.
> 
> I see. Not sure exactly of the details but would have expected it to work. The basic OS should not matter.
> Might be worth raising that as an issue to the rEFInd project.
> 
> Will look at the refindPlus issues properly later.
> 
> PS: To activate a token, you need to have it not commented and there is no need to experiment between commenting or not.
> The RefindPlus one works in a specific way in that the debug build always produces a log and therefore, if commented, there will still be one (at level 0). Look at the ReadMe file and the accompanying text in the config file to understand.

Hey, sorry, I completely missed this.
I will report it to its creator ASAP, then.

**Comment by billabongbruno** [comment] 2021-05-23 17:30
> Hello,
> 
> Just realised you are not loading any drivers ... can you retry with an ext4 driver?
> This would typically be needed

Hey there.
I did try it before, but as stated in the first comment, if I have any .efi driver present in the drivers_x64 folder, RefindPlus only shows a blank screen.

I can try again and let you know if the problem persists.

**Comment by dakanji** [comment] 2021-05-23 17:33
> if I have any .efi driver present in the drivers_x64 folder, RefindPlus only shows a blank screen.

That would be a bug that needs fixing so share the log of any such occurrence.
Might actually point at the root cause of your issue

**Comment by billabongbruno** [comment] 2021-05-23 17:44
> > if I have any .efi driver present in the drivers_x64 folder, RefindPlus only shows a blank screen.
> 
> That would be a bug that needs fixing so share the log of any such occurrence.
> Might actually point at the root cause of your issue

And here it is:
[21j23t3801.log](https://github.com/dakanji/RefindPlus/files/6528616/21j23t3801.log)

**Comment by dakanji** [comment] 2021-05-23 17:53
That's an earlier log before I asked you to remove some things as a workaround.
Can you generate one with those changes in place and share that instead?

**Comment by billabongbruno** [comment] 2021-05-23 17:56
> That's an earlier log from before I asked you to remove some items as a workaround for other issues.
> Can you generate one with those changes in place and share that instead?

I don't think it is.
There was no log file (I delete them after sending a copy to you).

This was the one that just got generated.

Even the numbering is different.

But I will give it one more go, nonetheless.

**Comment by billabongbruno** [comment] 2021-05-23 18:02
> That's an earlier log from before I asked you to remove some items as a workaround for other issues.
> Can you generate one with those changes in place and share that instead?

Here it is again.

It ends the exact same way:
[21j23t5805.log](https://github.com/dakanji/RefindPlus/files/6528630/21j23t5805.log)

**Comment by dakanji** [comment] 2021-05-23 18:04
> I don't think it is.

It wasn't indeed. Should have checked the timestamp.

Will have a look now. Thanks

**Comment by dakanji** [comment] 2021-05-23 18:23
Can you run this build of the current code base and share the log?
[X127-BOOTx64.efi.zip](https://github.com/dakanji/RefindPlus/files/6528662/X127-BOOTx64.efi.zip)

Rename as needed for your setup.

Thanks

**Comment by billabongbruno** [comment] 2021-05-23 18:38
> Can you run this build of the current code base and share the log?
> [X127-BOOTx64.efi.zip](https://github.com/dakanji/RefindPlus/files/6528662/X127-BOOTx64.efi.zip)
> 
> Rename as needed for your setup.
> 
> Thanks

I'm sorry, I'm confused.

Do you want me to replace my BOOTx64.efi on my Boot folder?

Won't that render my current "main" rEFInd boot process invalid?
I don't have any other boot manager installed and I don't want to be locked out of the system.

Or is to replace the current RefindPlus efi?

**Comment by dakanji** [comment] 2021-05-23 18:39
This is to replace RefindPlus.

**Comment by billabongbruno** [comment] 2021-05-23 18:45
> This is updated RefindPlus to replace your current RefindPlus.

Thank you for the clarification.

All done.

Here it is:
[21j23u3958.log](https://github.com/dakanji/RefindPlus/files/6528701/21j23u3958.log)

Some progress was indeed made, but it still halts on a blank (black for me, because of the theme).

But I can see in the log that the <null> strings are no more.

**Comment by dakanji** [comment] 2021-05-23 19:07
Please try X128 (Not expected to load btw, just logging items):
[X128-BOOTx64.efi.zip](https://github.com/dakanji/RefindPlus/files/6528751/X128-BOOTx64.efi.zip)

**Comment by billabongbruno** [comment] 2021-05-23 19:09
> Please try X128 (Not expected to load btw, just logging items):
> [X128-BOOTx64.efi.zip](https://github.com/dakanji/RefindPlus/files/6528751/X128-BOOTx64.efi.zip)

No worries, I wasn't making assumptions, I was just keeping you informed.

Will try X128 and get back to you.

**Comment by billabongbruno** [comment] 2021-05-23 19:17
> Please try X128 (Not expected to load btw, just logging items):
> [X128-BOOTx64.efi.zip](https://github.com/dakanji/RefindPlus/files/6528751/X128-BOOTx64.efi.zip)

So here it is:
[21j23v1038.log](https://github.com/dakanji/RefindPlus/files/6528771/21j23v1038.log)

NOTE:
It may be completely irrelevant for your findings / debugging, but...
I experimented something with the "main" version of rEFInd and found out that...

The same error is thrown (Starting vmlinuz-5.4.0.73-generic --> Using load options (....) ---> Error: Load Error while loading vmlinuz-5.4.0.73-generic --> Paused: Press Any Key to Continue)
when no
"volume" argument is added in the manual boot stanzas.

To make myself clearer:

"main" rEFInd WORKS IF:

"menuentry "Linux Mint 20.1" {
graphics on
icon /EFI/refindPlus/themes/refind-black/icons/os_linuxmint.png
volume 8804259d-cd36-4a0b-9afc-e0429e3b7319
loader /boot/vmlinuz-5.4.0-73-generic
initrd /boot/initrd.img-5.4.0-73-generic
options "ro root=UUID=196cb73c-2f3f-4a32-8a37-85051fe93225 ro fsck.mode=skip quiet splash"
}"

But it does NOT WORK IF:

"menuentry "Linux Mint 20.1" {
graphics on
icon /EFI/refindPlus/themes/refind-black/icons/os_linuxmint.png

loader /boot/vmlinuz-5.4.0-73-generic
initrd /boot/initrd.img-5.4.0-73-generic
options "ro root=UUID=196cb73c-2f3f-4a32-8a37-85051fe93225 ro fsck.mode=skip quiet splash"
}"

That being said, the "main" version of rEFInd does load the ext4 driver.

But the error thrown is the exact same in RefindPlus (when the driver is absent).

**Comment by dakanji** [comment] 2021-05-23 19:52
Few things
- You can simply use "RefindPlus" and "rEFInd" to differentiate.
- The driver is loaded by RefindPlus. It's just that the stanza crash happens earlier when it is loaded.
- Would expect a crash when volume is not present but will look at what RefindPlus is doing on that angle later.

For now, please run X129: [X129-BOOTx64.efi.zip](https://github.com/dakanji/RefindPlus/files/6528813/X129-BOOTx64.efi.zip)

Thanks

**Comment by billabongbruno** [comment] 2021-05-23 20:00
> Few things
> 
> * You can simply use "RefindPlus" and "rEFInd" to differentiate.
> * The driver is loaded by RefindPlus. It's just that the stanza crash happens earlier when it is loaded.
> * Would expect a crash when volume is not present but will look at what RefindPlus is doing on that angle later.
> 
> For now, please run X129: [X129-BOOTx64.efi.zip](https://github.com/dakanji/RefindPlus/files/6528813/X129-BOOTx64.efi.zip)
> 
> Thanks

I understand.
I was, however, just providing some info based on my experimentations.
As I said, could be of little to no consequence at all.

That being said, here is the new log file:

[21j23v5655.log](https://github.com/dakanji/RefindPlus/files/6528833/21j23v5655.log)

**Comment by dakanji** [comment] 2021-05-23 20:22
Thanks ... was just giving some initial feedback.

Anyway, something odd is happening and needs stepping back to consider.
The crashes are not happening at the same point which suggests something deeper than I initially thought.
Most likely a memory management issue.

Will look into some things and get back.

Thanks again.

**Comment by dakanji** [comment] 2021-05-23 20:51
Hi ... thank you very much again for helping with testing.
Would you mind trying this one as well?

Trying to eliminate an angle.

[X130-BOOTx64.efi.zip](https://github.com/dakanji/RefindPlus/files/6528901/X130-BOOTx64.efi.zip)

**Comment by billabongbruno** [comment] 2021-05-23 21:05
> Hi ... thank you very much again for helping with testing.
> Would you mind trying this one as well?
> 
> Trying to eliminate an angle.
> 
> [X130-BOOTx64.efi.zip](https://github.com/dakanji/RefindPlus/files/6528901/X130-BOOTx64.efi.zip)

Hey.
No worries.
Thank YOU for your work.

So...
I have some good news for you, but not so much for me, lol.

So this version does show all manually entered stanzas.
And I am able to enter Linux Mint, Ubuntu and Windows.
However, I cannot boot into MacOS anymore nor ChromeOS.

And for some reason, the damage has extended to rEFInd too, not only RefindPlus.

=/
[21j23w5818.log](https://github.com/dakanji/RefindPlus/files/6528913/21j23w5818.log)
[21j23w5848.log](https://github.com/dakanji/RefindPlus/files/6528914/21j23w5848.log)
[21j23w5918.log](https://github.com/dakanji/RefindPlus/files/6528915/21j23w5918.log)
[21j23x0024.log](https://github.com/dakanji/RefindPlus/files/6528916/21j23x0024.log)

**Comment by dakanji** [comment] 2021-05-23 21:12
Good to know this works.

There shouldn't be any thing affecting each other rEFInd and RefindPlus.
Perhaps the EFI files got mixed up while renaming etc. Just get a fresh copy of the rEFInd efi and replace if unsure.

> However, I cannot boot into MacOS anymore nor ChromeOS

Shouldn't be the case but do share logs from the failed attempts.

**Comment by billabongbruno** [comment] 2021-05-23 21:14
> Good to know this works.
> 
> There shouldn't be any thing affecting each other rEFInd and RefindPlus.
> Perhaps the EFI files got mixed up while renaming etc. Just get a fresh copy of the rEFInd efi and replace if unsure.
> 
> > However, I cannot boot into MacOS anymore nor ChromeOS
> 
> Shouldn't be the case but do share logs from the failed attempts.

I shared all the logs, even the ones containing the failed attempts.
As I said, I suspect along the way a NVRAM reset occurred.
I'm gonna try and fix the ChromeOS part now.

**Comment by billabongbruno** [comment] 2021-05-23 21:27
> Good to know this works.
> 
> There shouldn't be any thing affecting each other rEFInd and RefindPlus.
> Perhaps the EFI files got mixed up while renaming etc. Just get a fresh copy of the rEFInd efi and replace if unsure.
> 
> > However, I cannot boot into MacOS anymore nor ChromeOS
> 
> Shouldn't be the case but do share logs from the failed attempts.

ChromeOS is beyond repair now, but it's Ok, a simple reinstall will fix it, for sure.
Something must have corrupted the .img file after all the forced shutdowns and reboots.

It's of little matter.
15 minutes will be enough to fix it.

Thank you very much for all your help and work.

After the ChromeOS fresh install I will report back again.

See you soon.

**Comment by billabongbruno** [comment] 2021-05-23 21:30
> Hi ... thank you very much again for helping with testing.
> Would you mind trying this one as well?
> 
> Trying to eliminate an angle.
> 
> [X130-BOOTx64.efi.zip](https://github.com/dakanji/RefindPlus/files/6528901/X130-BOOTx64.efi.zip)

Whilst ChromeOS part is ongoing, I have to admit...
I am very curious to know which angle it was that you tried (and succeeded) in eliminating.

What was wrong?

**Comment by dakanji** [comment] 2021-05-23 21:36
> What was wrong?

Something was off in the manual stanza scanning code.
I did a wholesale reset to confirm suspicion and now have to get to the exact issue.

Will need a few more test runs if you are still willing!

Also have to close out the "firmware_bootnum" Feature failure although might be linked.

**Comment by billabongbruno** [comment] 2021-05-23 21:43
> > What was wrong?
> 
> Something was off in the manual stanza scanning code.
> I did a wholesale reset to confirm suspicion and now have to get to the exact issue.
> 
> Will need a few more test runs if you are still willing!
> 
> Also have to close out the "firmware_bootnum" Feature failure although might be linked.

Oh, that's a nice catch.

Also, just a little FYI:

Windows sucks.
Why?

Because Chrome was not booting because of Windows?
How come?

Well, I created my EFI partition prior to installing Windows itself (to have the size I wanted).
Then proceeded to install Windows.
Windows created the 16Mb MSR partition and its own install partition (obviously), NOT HAVING CREATED THE RECOVERY PARTITION (which was intentional).
So.... I have recently updated to 21H1 version (I had 20H2) and guess what?

Windows reduced its install patition and created a Recovery partition between itself and the others.
Seeing as the Linux partitions had unique UUIDs and MacOS was pointing to an EFI file, everything loaded without a hitch.

ChromeOS, on the other hand, is chainloaded through RefindPlus --> GRUB.
Grub's menuentry was pointing to "nvme partition 4", which was NOW NOT TRUE ANYMORE.
It was now partition 5.

THANKS, WINDOWS.

It's fixed.
A simple matter of editing the grub.cfg using one of my Linux Distros.

This info might not be relevant for you, but who knows, someone might come across this same issue some day and come here and find the solution.

That said, I am more than happy to help with debugging.

Cheers.

**Comment by dakanji** [comment] 2021-05-23 21:56
Thanks for the heads up.

Will pick up on things later.

**Comment by dakanji** [comment] 2021-05-24 18:18
Done a few tests and got the fix for this issue sorted.
Will push a commit to close this presently.

Thanks for reporting and helping with debugging the issue.

**Comment by billabongbruno** [comment] 2021-05-24 21:15
> Done a few tests and got the fix for this issue sorted.
> Will push a commit to close this presently.
> 
> Thanks for reporting and helping with debugging the issue.

Glad to know everything worked out after your tests.

Don't mention it.

Also, thank you a lot for all your hard work, patience and help.
Let me know if I can be of any help in this or other projects you have.

Best regards,
Bruno.

**Closed** 2021-05-24 22:06 UTC
Labels: Bug
