### ISSUE TITLE
RefindPlus Freezes when Scanning Linux Disk

### ISSUE THREAD

**Issue by Macschrauber** [dakanji/RefindPlus#45] opened 2021-04-06 15:21 UTC
**Describe the Bug:**

Linux Disk or EXT4 Driver let RP v0.13.2.AA freeze
Linux Disk (a dedicated Sata drive) let RP freeze.

**Environment:**

 - RefindPlus Version : v0.13.2.AA
 - Hardware
   * Computer         : MacPro 3,1
   * Motherboard      : Apple OEM
   * GPU Model        : Nividia Quadro K2000 UGA (Mac EFI Bootscreen)
   * GPU Port         : [DVI-I]
   * GPU Flash        : Yes-Self
 - Affected OS        : EFI

**Log and Config Files**

[21h06q0856.log](https://github.com/dakanji/RefindPlus/files/6265721/21h06q0856.log)
[Archive.zip](https://github.com/dakanji/RefindPlus/files/6266674/Archive.zip)
[Archive.zip](https://github.com/dakanji/RefindPlus/files/6266665/Archive.zip)

**Screenshots**

added a log in Log Level 4, config Files and a Screenshot

**Additional Context:**

MyBootMgr 068 Package
Tested the ext4 driver from 067 Package, same freeze.
It works when the Ext4 driver is removed.

**Comment by dakanji** [comment] 2021-04-06 15:51
Can you please edit to follow the issue template and in your case, also provide a log at Level 4?

Thanks

**Comment by Macschrauber** [comment] 2021-04-06 17:33
Its not freezing when _booting_ Linux, it is freezing when rp finds a disk with Linux on it. It does not work at all.

**Comment by dakanji** [comment] 2021-04-06 17:42
> Its not freezing when booting Linux, it is freezing when rp finds a disk with Linux on it. It does not work at all.

Amended the title. Started off the edit. Please complete.

Thanks

**Comment by dakanji** [comment] 2021-04-06 18:08
> added a log in Log Level 4, config Files and a Screenshot

Can't find these.

**Comment by dakanji** [comment] 2021-04-06 18:27
Can you confirm this works with v0.13.1.AB?

**Comment by Macschrauber** [comment] 2021-04-06 18:40
> Can you confirm this works with v0.13.1.AB?

Yes

**Comment by dakanji** [comment] 2021-04-06 21:38
Ok ... run X116 and share the log (Level 4).


[X116-BOOTx64.efi.zip](https://github.com/dakanji/RefindPlus/files/6267694/X116-BOOTx64.efi.zip)

**Comment by Macschrauber** [comment] 2021-04-07 09:06
> Ok ... run X116 and share the log (Level 4).
> 
> [X116-BOOTx64.efi.zip](https://github.com/dakanji/RefindPlus/files/6267694/X116-BOOTx64.efi.zip)

same freeze

[21h07i5924.log](https://github.com/dakanji/RefindPlus/files/6270371/21h07i5924.log)

**Comment by dakanji** [comment] 2021-04-07 09:35
Thanks. Please run X117and share the log.

BTW, Neither this nor the one before contain any attempted fixes and only have additional logging items to shed light on what is happening.

[X117-BOOTx64.zip](https://github.com/dakanji/RefindPlus/files/6270512/X117-BOOTx64.zip)

**Comment by Macschrauber** [comment] 2021-04-07 10:16
> Thanks. Please run X117and share the log.
> 
> BTW, Neither this nor the one before contain any attempted fixes and only have additional logging items to shed light on what is happening.
> 
> [X117-BOOTx64.zip](https://github.com/dakanji/RefindPlus/files/6270512/X117-BOOTx64.zip)

[21h07k1059.log](https://github.com/dakanji/RefindPlus/files/6270772/21h07k1059.log)

**Comment by dakanji** [comment] 2021-04-07 10:33
It doesn't look like you are at Log Level 4

**Comment by Macschrauber** [comment] 2021-04-07 10:49
> It doesn't look like you are at Log Level 4 ... Looks like you have Level 3.

I have set

log_level 4

in custom.conf

**Comment by dakanji** [comment] 2021-04-07 11:25
> I have set log_level 4 ... no difference

It's a bug.
It is picking the level immediately below what is entered. 
Temporarily set to Level 5 to get Level 4 logging pending a fix.

Thanks

**Comment by Macschrauber** [comment] 2021-04-07 12:41
now it's getting complicated:

X117 in Log Level "5" is ok (!), got no freeze, rebooted about 10 times
[x117 log level 5.zip](https://github.com/dakanji/RefindPlus/files/6271597/x117.log.level.5.zip)

X117 in Log Level 4 is freezing
[x117 log level 4 = freeze.zip
(https://github.com/dakanji/RefindPlus/files/6271603/x117.log.level.4.freeze.zip)



X116 in Log Level 5 has been working 4 times out of 5, at least I got it one time to freeze
[X116 log level 5 - 1 time freeze.zip](https://github.com/dakanji/RefindPlus/files/6271608/X116.log.level.5.-.1.time.freeze.zip)




Maybe a timing thing what does get sorted when writing more logs. This would explain why it worked for me at first attempt with v0.13.2.AA and after warm boot no more.



I even tried v0.13.2.AA in Release Version, it freezed, no logs here of course.

**Comment by dakanji** [comment] 2021-04-07 13:05
I need to look in more detail and will request more tests later.

For now, you should be able to bypass the issue by setting `fold_linux_kernels 0`
This will give you two instances of your kernels of your Linux instance instead of combining them into one.

**Comment by Macschrauber** [comment] 2021-04-07 13:25
> I need to look in more detail and will request more tests later.
> 
> For now, you should be able to bypass the issue by setting `fold_linux_kernels 0`
> This will give you two separate instances of the two kernels of your Linux instance instead of combining them into one.

Yes, that worked for v0.13.2.AA

**Comment by dakanji** [comment] 2021-04-07 14:47
Please try X118 which includes an attempted fix.
Set `fold_linux_kernels 1`.

**Comment by Macschrauber** [comment] 2021-04-07 18:31
X118 worked way of

toggled Linux 3.16 / 4.4 on some reboots
Booted Linux 4.4 ok
freezed once like v0.13.2.AA like the issue topic
freezed after about screen

[X118.zip](https://github.com/dakanji/RefindPlus/files/6273769/X118.zip)

**Comment by dakanji** [comment] 2021-04-08 05:03
@startergo ... can you help with a copy of a snapshot of the current upstream code?

@Macschrauber ... I believe startergo has a build of the current upstream code up his sleeve and once he hopefully posts this, can you try running that? I suppose this might need to be chain loaded via OpenCore.

Make sure `fold_linux_kernels` is either commented out or set to 1

**Comment by startergo** [comment] 2021-04-08 10:51
[refind.zip](https://github.com/dakanji/RefindPlus/files/6278040/refind.zip)
Attached the compiled folder.

**Comment by dakanji** [comment] 2021-04-08 12:17
@startergo ... sorry. need the compiled efi.

**Comment by dakanji** [comment] 2021-04-09 01:51
@Macschrauber ... here is the one we needed of the few hundred received!
[refind_x64.efi.zip](https://github.com/dakanji/RefindPlus/files/6282625/refind_x64.efi.zip)

**Comment by Macschrauber** [comment] 2021-04-09 06:10
Can test it tomorrow.

**Comment by dakanji** [comment] 2021-04-09 06:55
Actually, you can put the upstream test aside for a while for X119 as I think I may have found something that may be the cause.

[X119-BOOTx64.efi.zip](https://github.com/dakanji/RefindPlus/files/6283729/X119-BOOTx64.efi.zip)

**Comment by Macschrauber** [comment] 2021-04-10 16:17
same freeze with x119a

fold_linux_kernels set to 1

Added another freeze log for x118

[Archive.zip](https://github.com/dakanji/RefindPlus/files/6290254/Archive.zip)

**Comment by Macschrauber** [comment] 2021-04-10 16:34
> @Macschrauber ... here is the one we needed of the few hundred received!
> [refind_x64.efi.zip](https://github.com/dakanji/RefindPlus/files/6282625/refind_x64.efi.zip)


tried it also, it works but seams to does not load ext4 Driver, so no Linux is scanned.

duplicating config.conf to refind.conf didnt helped loading the driver. Maybe you guys can give me a setting for loading ext4 driver to Refind

for the record a Refind log:

[refind.log](https://github.com/dakanji/RefindPlus/files/6290285/refind.log)

**Comment by Macschrauber** [comment] 2021-04-10 17:26
found it,
RP named drivers folder: x64_drivers
rEFInd name drivers folder: drivers_x64

Linux works with Linux, showed vmlinuz-4.4.0-138-generic

so the rEFInd upstream code had no freeze with Linux
Also get info did not returned a freeze btw

rEFInd Log from working Linux Scan:
[refind.log](https://github.com/dakanji/RefindPlus/files/6290398/refind.log)

**Comment by dakanji** [comment] 2021-04-10 19:46
> RP named drivers folder: x64_drivers

Drivers folder can be x64_drivers, drivers or drivers_x64 in RP but yes, MyBootMgr sets up x64_drivers

Anyway, the rEFInd build was not from snapshot of the current code and unfortunately the test is not what was needed.

**Comment by dakanji** [comment] 2021-04-10 20:27
So you understand what is happening, rEFInd, and RefindPlus by association, has a facility to combine related Linux kernels and display only one of these when "fold_linux_kernels" is active. This feature was added in rEFInd 0.9.0 (Jul 2015).

You can access the other kernels by pressing "F2" when the icon is highlighted but due to a bug in the code, you do not get a "Return to Main Menu" option when you do this as is supposed to be. 

Basically, a bit of code to add the option was never run due to an error and I pushed a commit upstream to fix this bug on [04 Apr 2021](https://sourceforge.net/p/refind/code/ci/87f5eb87565da8c16832a2d8f03e3d22ea389c2a/) and the same fix was implemented in RefindPlus and included in 0.13.2.AA.

The bug is present in up to RefindPlus 0.13.1.AB and in the current rEFInd release, v0.13.1.

When you run 0.13.2.AA, that piece of code that was wrongly never being run is now run when "fold_linux_kernels" is active but this has uncovered a more serious issue leading to a hang.

In order to determine whether the issue is local to RefindPlus, we need to test a rEFInd build that includes this fix. That is, a build on rEFInd from after 04 Apr 2021 which is why i requested something from the current codebase.

Unfortunately, the build from @startergo does not include the bug fix (it is from code before this). You can verify by pressing F2 and you will not have a  "Return to Main Menu" option.

I will park this issue until it is possible to properly investigate but will try to identify any memory management conflicts that can be causing this hang. The one causing the About screen to hang has been resolved in v0.13.2.AB and the "Return to Main Menu" option disabled there so it should work for you in the interim.

**Comment by startergo** [comment] 2021-04-10 20:59
[refind_x64.efi.zip](https://github.com/dakanji/RefindPlus/files/6290744/refind_x64.efi.zip)
This is the latest refind

**Comment by dakanji** [comment] 2021-04-11 07:45
Thanks @startergo 
@Macschrauber ... can you test this version?

**Comment by Macschrauber** [comment] 2021-04-11 09:28
> Thanks @startergo
> @Macschrauber ... can you test this version?

it works exactly as the previous refind 0.13.2.6 version I tested from @startergo

Log (0.13.2.7)

[refind.log](https://github.com/dakanji/RefindPlus/files/6291454/refind.log)

**Comment by dakanji** [comment] 2021-04-11 09:47
> it works exactly as the previous refind 0.13.2.6 version

The purpose of test runs in to get information and until 0.13.2.7 was run, there was no way to exactly know whether that change has an impact there or not. 

Anyway, can you confirm you got the "Return to Main Menu" Option as It doesn't appear it specifically logs this action?
Also, please run X120 and share the log. 

[X120-BOOTx64.efi.zip](https://github.com/dakanji/RefindPlus/files/6291478/X120-BOOTx64.efi.zip)

**Comment by Macschrauber** [comment] 2021-04-11 13:16
However, can you confirm you got the "Return to Main Menu" Option as It doesn't appear it specifically logs this action?

return to main menu worked with 0.13.2.7, I even stress tested the action by triggering it a dozen or so times.

**Comment by Macschrauber** [comment] 2021-04-11 13:26
> 
> 
> 
> Also, please run X120 and share the log.
> 
> [X120-BOOTx64.efi.zip](https://github.com/dakanji/RefindPlus/files/6291478/X120-BOOTx64.efi.zip)



with fold_linux_kernels 1 X120 still freezes into scanning Linux
[21h11p1834.log](https://github.com/dakanji/RefindPlus/files/6291860/21h11p1834.log)

**Comment by Macschrauber** [comment] 2021-04-11 17:41
Update: by looking into the log and the /icons folder I found that there was no

os_boot.*

icon, no os_boot.png, os_boot.jpg and so on. Used latest MyBootMgr package to install RP.

so copied os_linux.png to os_boot.png and got RP X120 with fold_linux_kernels 0 to boot (what freezed also)

got too linux instances with those two kernels btw

is it a bug that RP freezes if there's no corresponding icon in /icon ?

test with fold_linux_kernels 1 if not Macschrauber's wife yelling out the kitchen :-)

[x120 21h11t3401.log](https://github.com/dakanji/RefindPlus/files/6292393/x120.21h11t3401.log)

**Comment by Macschrauber** [comment] 2021-04-11 18:38
X120 with fold_linux_kernels 1 is still freezing

[x120 freeeze 21h11u3404.log](https://github.com/dakanji/RefindPlus/files/6292512/x120.freeeze.21h11u3404.log)

**Comment by dakanji** [comment] 2021-04-11 18:47
Please run X121 and share the log
[X121-BOOTx64.efi.zip](https://github.com/dakanji/RefindPlus/files/6292524/X121-BOOTx64.efi.zip)

Ps: Issue is not related to icons. Delete the os_boot.xyz file you created.

**Comment by Macschrauber** [comment] 2021-04-11 18:47
As thinking about icons I tried textonly, it's freezing in "initializing"

[21h11u4355.log](https://github.com/dakanji/RefindPlus/files/6292531/21h11u4355.log)

**Comment by Macschrauber** [comment] 2021-04-11 19:58
> Please run X121 and share the log
> [X121-BOOTx64.efi.zip](https://github.com/dakanji/RefindPlus/files/6292524/X121-BOOTx64.efi.zip)
> 
> Ps: Issue is not related to icons. Delete the os_boot.xyz file you created.

tested x121, same freeze

[x121 21h11v5148.log](https://github.com/dakanji/RefindPlus/files/6292659/x121.21h11v5148.log)

**Comment by Macschrauber** [comment] 2021-04-11 20:16
as a side note:

tested X121 with fold_linux_kernels 0 and without os_boot.png,
this time it worked and it wrote to os_boot.xyz not found to the log, also Linux icons matched.

and a 2nd side note: Return to Main Menu in get info worked.

log for X121 with fold_linux_kernels_0
[X121 21h11w0947.log](https://github.com/dakanji/RefindPlus/files/6292689/X121.21h11w0947.log)

**Comment by dakanji** [comment] 2021-04-11 20:42
X121 didn't include fixes and just had additional logging but try X122 which does ... along with extra logging.

[X122-BOOTx64.efi.zip](https://github.com/dakanji/RefindPlus/files/6292736/X122-BOOTx64.efi.zip)

**Comment by Macschrauber** [comment] 2021-04-12 05:48
> X121 didn't include fixes and just had additional logging but try X122 which does ... along with extra logging.
> 
> [X122-BOOTx64.efi.zip](https://github.com/dakanji/RefindPlus/files/6292736/X122-BOOTx64.efi.zip)

It works :-)

With fold_linux_kernels 0 two VMlinuz Menu entries with both Kernels, Return to Main Menu ok
[X121 fold 0 21h12f3059.log](https://github.com/dakanji/RefindPlus/files/6294208/X121.fold.0.21h12f3059.log)


With fold_linux_kernels 1 one VMlinuz Menu entry(both Kernels via Submenu), Return to Main Menu ok
[x121 fold 1 21h12f3635.log](https://github.com/dakanji/RefindPlus/files/6294215/x121.fold.1.21h12f3635.log)

**Closed** 2021-04-12 09:48 UTC
Labels: Bug
