### ISSUE TITLE
v0.13.2.AP: Pre-Release build does not display screen on MacPro5,1 with RX580

### ISSUE THREAD

**Issue by mark-heiple** [dakanji/RefindPlus#110] opened 2022-05-02 03:39 UTC
### RefindPlus Version

Pre-Release Code Build

### Device Type

Apple Mac

### Problem Description

I am using the version of RefindPlus as installed by MyBootMgr, whatever version was available on 4/16/2022.

I used MyBootMgr to install RefindPlus, for the purpose of getting a boot screen so that I can dual boot between macOS High Sierra and Linux Mint 20. I'm not interested in installing newer unsupported versions of macOS.

My mac has both an RX580 (in the x16 bottom slot) and a HD 5770 (in the 2nd x4 slot). When the monitor is connected to the HD5770, everything is fine. Plugged into the RX580 - nothing. The numeric keys don't start any OS either.

I had used refind before using MyBootMgr to install refindPlus. I thought I had cleared out all the previous refind files from the EFI volume, buy maybe not. The /BOOT/BOOTx64.efi file appears to be the one installed by MyBootMgr. The boot screen identifies itself as RefindPlus, not Refind.

With only the HD5770, or both the HD5770 and the RX580 installed and the monitor attached to the HD5770 I get a boot screen and can successfully boot both Linux and macOS.

With both video cards installed and the monitor attached to the RX580, I get no boot screen - screen stays dark. Number 4 on the keyboard should start macOS, 5 Linux with my setup. However pressing both 4 and 5 does not start either OS.

I tried removing the HD5770, so only the RX580 is installed. I still get no boot screen and the keyboard commands to select an OS don't work.

Before installing OpenCore/RefindPlus, macOS would boot with the RX580 (and without the HD5770) but does not display a boot screen.

### Problem Point

Before RefindPlus loads

### Affected Items

Other

### Debug Log

[opencore-2022-04-16-164315.txt](https://github.com/dakanji/RefindPlus/files/8600671/opencore-2022-04-16-164315.txt)
[22h23t1247.log](https://github.com/dakanji/RefindPlus/files/8600675/22h23t1247.log)

**Comment by dakanji** [comment] 2022-05-02 06:46
Was your RX580 bought new or used?

**Comment by mark-heiple** [comment] 2022-05-02 12:59
It was bought new as a factory installed item when I bought the Mac Pro (used) from OWC

**Comment by dakanji** [comment] 2022-05-02 13:29
Good. Used examples can have had the VBIOS modified for crypto mining and assuming you have not modified the VBIOS yourself, it is showing some odd characteristics, we can park that item for now.

Firstly, apologies for being preachy, you have to at least know the version of stuff you are running on your machine with respect to this: `whatever version was available on 4/16/2022`. If you don't or have forgotten, you should be able to go back to look at the file you downloaded as this will have the version string.

Anyway, I happen to know that there has been an update since 16 Apr 2022 (I assume that is what 4/16/22 refers to). So, download the current version and try again with that.

If trying MacOS directly from RefindPlus fails, try blindly booting into OpenCore (use Key 1) and give an update on the outcome.

**Comment by dakanji** [comment] 2022-05-04 13:19
Yes, you could just position and rename if you prefer.

This may mean you account for any changes in the config file for that version and given the request for an OpenCore test, that the current version of OpenCore and any configuration fixes for OpenCore addressed in the current version of MyBootMgr from the one you originally used are also taken care of.

You can find releases of projects on GitHub by following the `Releases` link on the main GitHub page of such projects.

**Comment by mark-heiple** [comment] 2022-05-09 13:18
I haven't had a chance to do much further experimenting but plan to this week. Just copying over the new RefindPlus did not work, refindplus did not load and it reverted to the Apple boot manager. Blessing it again also failed, the message was something about it not being valid. I downloaded MyBootMgr 080, recreated a config and deployed it. I have it working again, the next step will be to swap out the HD5770 for the RX 580 and see if it works. I am waiting for a usb-c card to arrive, which I will install at the same time.

I've attached the config that was generated and the latest boot log to verify that the config is valid.

[22j08f5320.log](https://github.com/dakanji/RefindPlus/files/8652018/22j08f5320.log)
[config.conf.txt](https://github.com/dakanji/RefindPlus/files/8652022/config.conf.txt)
[custom.conf.txt](https://github.com/dakanji/RefindPlus/files/8652024/custom.conf.txt)
[DebugLog_ConfigFactory.log](https://github.com/dakanji/RefindPlus/files/8652031/DebugLog_ConfigFactory.log)

**Comment by dakanji** [comment] 2022-05-09 15:23
The partitions stuff is highly unlikely to be a factor on getting a display before selecting a loader.

1. Did you try booting with Key 1 to run OpenCore?
2. Just struck me to ask that when you say you have disconnected the HD5770, does this mean you have physically removed it from the Mac or just that you disconnected the supplementary power to the GPU?

Note that simply disconnecting the supplementary power may not necessarily mean disconnection. That cable supplies additional power but bear in mind that power is drawn from the PCI slot and if the GPU is sitting there connected to the slot, it may not be totally deactivated ... Just something to consider.

**Comment by dakanji** [comment] 2022-05-09 16:39
From your ConfigFactory log:
```
Model_GPU:- AMD Radeon HD 5770 ... Legacy_AMD:- true
```

It is building your OpenCore config based on the HD5770.

That is, it is findable and seems you definitely need to physically remove it.

**Comment by startergo** [comment] 2022-05-09 17:33
Hd 5770 needs To be removed from the PCIE slot if you have RX-580 installed.

**Comment by dakanji** [comment] 2022-05-10 07:33
Another item that crossed my mind is that I don't think the RX580 is actually properly supported by HiSierra in the first place and that you need to be on Mojave for full support.

Issue seems invalid

**Comment by mark-heiple** [comment] 2022-05-10 13:02
Everything I've read says High Sierra is the minimum version that supports the RX580, but it is fully supported. I don't want to go to Mojave because I want to keep my system HFS+.

**Comment by mark-heiple** [comment] 2022-05-11 00:56
I've never seen anything saying that the RX580 is not fully supported.

But in any case, I plugged in the RX580 and removed the HD5770 -- and no screen. Keypresses don't start anything either, it just sits there dead to the world.

I have no idea what else to try - I need working video to set up a MyBootMgr configuration - which only works with the HD5770.

**Comment by mark-heiple** [comment] 2022-05-11 01:54
Did some more fiddling, and discovered that for some reason the RX580 isn't outputting video from the DVI port, but does (when booting macos) output from the HDMI  ports. I was able to boot into macOS with just the RX580, created and installed a new MyBootMgr configuration. Still no boot screen. Pressing 4 successfully boots macOS and I get video. Soft blessed and rebooted, this time tried pressing 1 to get into opencore. Still no video, and couldn't get anything to boot since I couldn't see the menu. The following files are the logs, plus the result of the 'press 4' and 'press 1' runs.
[22j11b3307 (4 to boot macos).log](https://github.com/dakanji/RefindPlus/files/8666063/22j11b3307.4.to.boot.macos.log)
[22j11b4111 (1 to boot opencore).log](https://github.com/dakanji/RefindPlus/files/8666064/22j11b4111.1.to.boot.opencore.log)
[config.conf.txt](https://github.com/dakanji/RefindPlus/files/8666065/config.conf.txt)
[custom.conf.txt](https://github.com/dakanji/RefindPlus/files/8666066/custom.conf.txt)
[DebugLog_ConfigFactory.log](https://github.com/dakanji/RefindPlus/files/8666067/DebugLog_ConfigFactory.log)
[opencore-2022-05-11-011857 (4 to boot macos).txt](https://github.com/dakanji/RefindPlus/files/8666068/opencore-2022-05-11-011857.4.to.boot.macos.txt)
[opencore-2022-05-11-014102 (1 to boot opencore).txt](https://github.com/dakanji/RefindPlus/files/8666069/opencore-2022-05-11-014102.1.to.boot.opencore.txt)

**Comment by dakanji** [comment] 2022-05-11 05:21
Thanks.

From the log output, your RX580 is definitely non-standard ... Could it be the 'Lite' Edition?
https://forums.macrumors.com/posts/28515375
Probably not as those apparently do not have DVI ports at all.

Main issue is that unlike what is typical, your unit is not doing anything that will make it possible to show a screen until MacOS starts loading.

What is expected on a GPU using GOP such as the RX580 is that around the time you hear the chime, GOP is initialised but you don't get a screen until MacOS starts loading under normal a setup. Tools such as Refindplus and OpenCore can however use this GOP presence to display a screen. 

When this initialisation has not taken place, GOP will be missing on device handles
```
Could Not Find Path to GOP on Any Device Handle
```

Alternatively, this initial GOP setup may been attempted but failed on a Legacy MacPro. In such cases, the OptionROM will still be stting in the RAM. RefindPlus applies a fix for the typical cause of such failures, gets the OptionROM from the RAM and reruns it.

In your case, there was no OptionROM in the RAM
```
Acquire OptionROM on Volatile Storage ... Not Found
```
This says an attempt had not been made to init GOP by the time the bootloader started.

There are some other different things but anyway, run through the following tests one after the other:
1. RX580 should be dual BIOS. Try to find the BIOS Switch (it is tiny and easily missed),  switch to the other VBIOS and see if this makes a difference. The alternative VBIOS typically does not work well on Macs at least but worth a try.
2.  Eliminate the chance that RefindPlus is responsible for the screen not showing by blessing OpenCore with the BootBleesser app. This removes RefindPlus from the boot chain and loads OpenCore directly.

Note that you can boot blindly into OpenCore. Unfortunately, it is not yet clear how the arrangement is determined so you just have to start from Key 1 and work towards 9 untill you hit the OS you want. You have to reboot each time you get it wrong obviously. 

If those two do not change things, I don't expect they would btw, then it is the case that your RX580 simply cannot provide the screen. 

One option that might work for you is to set the `text_only` token in RefindPlus which would probably work to give a text based but clear working way to select your load options.

Since you do not appear to actually need OpenCore, you can then delete the OpenCore folders and remove the relevant entries from the RefindPlus config file. On future updates, just replace the BOOTx64 file. Remember to switch to REL to avoid your ESP getting clogged up by log files over time.

**Comment by startergo** [comment] 2022-05-11 11:09
```
Found 2 pointer devices - Success
00:796 00:010 OCC: GOP exists on ConsoleOutHandle and has 0 modes
00:806 00:010 OCC: Looking for GOP replacement due to invalid mode count
00:817 00:010 OCC: Alternative GOP status is - Not Found
00:826 00:009 OCC: Missing compatible GOP - Not Found
00:836 00:009 OC: Requested resolution is 0x0@0 (max: 1, force: 0) from Max
00:847 00:011 OCC: Requesting 0x0@0 (max: 1) resolution, curr 0, total 0
00:858 00:011 OCC: Current FB at 0x0 (0x0), format 0, res 0x0 scan 0
00:870 00:011 OCC: No compatible mode for 0x0@0 (max: 1) resolution
00:880 00:010 OC: Changed resolution to 0x0@0 (max: 1, force: 0) from Max - Not Found
00:891 00:010 OCC: Found 1 handles with UGA draw
00:900 00:009 OCC: Found 1 handles with GOP for UGA check
00:909 00:009 OCC: Trying handle 0 - 75D6BA98
00:919 00:009 OCC: Skipping UGA proxying as it is already present on handle 0 - 75D6BA98
00:928 00:009 OCC: Using builtin text renderer with 1 scale
00:940 00:011 OCC: ASCII Text Reset [RenderResync] - Load Error
00:951 00:011 OCC: Setup ASCII Output - Load Error
00:962 00:010 OC: Requested console mode is 0x0 
```
where is this UGA draw coming from?

```
00:891 00:010 OCC: Found 1 handles with UGA draw
00:900 00:009 OCC: Found 1 handles with GOP for UGA check
00:909 00:009 OCC: Trying handle 0 - 75D6BA98
00:919 00:009 OCC: Skipping UGA proxying as it is already present on handle 0 - 75D6BA98
```
That is only on real Mac cards.

**Comment by dakanji** [comment] 2022-05-11 11:32
The stuff about compatible GOP had been gone over in RefindPlus

On this:
> where is this UGA draw coming from?

See:
> There are some other different things

I had to stop listing stuff somewhere and cut it short.

> Maybe he can test these settings

Will not make a difference. The issue is fundamental and beyond tinkering at the edges.
GOP is not installed. Full stop.

Only real hope for being able to select loaders is to use text mode ... unless switching the VBIOS works.

**Comment by startergo** [comment] 2022-05-11 11:35
First OC log says there is GOP handle:
```
Connecting drivers done...
00:856 00:013 OC: Found 3 pointer devices - Success
00:869 00:012 OCC: GOP exists on ConsoleOutHandle and has 1 modes
00:881 00:012 OC: Requested resolution is 0x0@0 (max: 1, force: 0) from Max
00:894 00:012 OCC: Requesting 0x0@0 (max: 1) resolution, curr 0, total 1
00:907 00:013 OCC: Current FB at 0x80010000 (0x40000000), format 1, res 1920x1080 scan 1920
00:920 00:013 OCC: Mode 0 - 1920x1080:1
00:934 00:013 OCC: Current mode matches desired mode 0
00:947 00:013 OC: Changed resolution to 0x0@0 (max: 1, force: 0) from Max - Already started
00:960 00:012 OCC: Found 3 handles with UGA draw
00:972 00:012 OCC: Found 2 handles with GOP for UGA check
00:985 00:012 OCC: Trying handle 0 - 75D6BC18
00:998 00:013 OCC: Skipping UGA proxying as it is already present on handle 0 - 75D6BC18
01:012 00:013 OCC: Trying handle 1 - 75B3B718
01:025 00:013 OCC: Skipping UGA proxying as it is already present on handle 1 - 75B3B718
01:039 00:013 OCC: Using builtin text renderer with 1 scale
01:104 00:065 OCC: Install console control (7356D920/0/0), current - Success
01:116 00:012 OCC: Setup ASCII Output - Success
01:129 00:012 OC: Requested console mode is 0x0 (max: 0) 
```

**Comment by mark-heiple** [comment] 2022-05-11 13:10
How do I extract the vbios? I don't have a PC, if that is required to do it.

**Comment by startergo** [comment] 2022-05-11 14:11
AMD/ATI BIOS ROM:
```
ioreg -arw0 -d1 -n display | xpath '//key[.="ATY,bin_image"]/following-sibling::*[1]/text()' | base64 -D -o ~/Desktop/vbios.rom
```
or 

```
ioreg -arw0 -d1 -n GFX0 | xpath '//key[.="ATY,bin_image"]/following-sibling::*[1]/text()' | base64 -D -o ~/Desktop/vbios.rom

**Comment by dakanji** [comment] 2022-05-11 18:10
> First OC log says there is GOP handle

MP51 comes with GOP on the ConsoleOut handle. 
```
   0:605    0:046  ConsoleOut Modes:
                     - Mode = Text           : YES
                     - Mode = Graphics (UGA) :  NO
                     - Mode = Graphics (GOP) : YES
                     ...

```
The ConsoleOut handle is not the GPU and this ConsoleOut GOP needs to be replaced. This is how the screen is provided on MP51.

```
                     - Seek Graphics Output Protocol
                       * Seek on ConsoleOut Handle ... Success
                     - Assess Graphics Output Protocol ... NOT OK!!

   8:336    0:219  Seek Replacement GOP Candidates:

   8:367    0:030  INFO: Could Not Find Usable Replacement GOP
```

A search for usable GOP candidate on the GPU turned out a blank.

@mark-heiple ... I need to keep things on track so I can conclude on this issue.
So before getting into extraction of VBIOS, please run the tests requested earlier and give feedback.

**Comment by dakanji** [comment] 2022-05-11 22:02
Right, based on available information, the conclusion is that the inability to show the screen is not RefindPlus related and to do with the GPU. This will be tagged as invalid and subsequently closed.

You can provide the VBIOS dump and continue on the discussion item you created before.

**Closed** 2022-05-11 22:10 UTC
Labels: Invalid
