### ISSUE TITLE
PreviousBoot Not Updated After Selecting Different Loader

### ISSUE THREAD

**Issue by volcbs** [dakanji/RefindPlus#69] opened 2021-08-14 14:56 UTC
**Describe the Bug:**
It seems that PreviousBoot file in /vars/ doesn't get written when you select a new booted loader. That makes RefindPlus doesn't remember what previous booted loader is and keeps selecting the first selected booted loader.

**To Reproduce:**
1. Keep everything as default for boot setting (meaning it should ignore "ignore_previous_boot" flag and create PreviousBoot file as default)
2. Boot to OS "A" (first picked booted loader)
3. Restart then boot to OS "B"
4. Wait until RefindPlus pick the booted loader from the PreviousBoot file

**Expected Behaviour:**
RefindPlus will select the first picked booted loader (OS "A"), despite previously we pick OS "B" to load.

**Environment:**

 - RefindPlus Version : v0.13.2.AG
 - Hardware
   * Computer         : Lenovo 510S-14ISK
   * CPU Model      : Intel i7-6500U
   * GPU Model        : Intel HD520 and AMD RADEON M460
 - Affected OS        : Opencore and Windows 10 (UEFI)

**Log Files**

[log0_BootToOS_B.log](https://github.com/dakanji/RefindPlus/files/6986643/log0_BootToOS_B.log)
[log4_BootToOS_B.log](https://github.com/dakanji/RefindPlus/files/6986641/log4_BootToOS_B.log)
[log0_BootToPreviousBoot.log](https://github.com/dakanji/RefindPlus/files/6986642/log0_BootToPreviousBoot.log)
[log4_BootToPreviousBoot.log](https://github.com/dakanji/RefindPlus/files/6986640/log4_BootToPreviousBoot.log)

**Screenshot**:
Look at the file date for respected files:
PreviousBoot
![Screenshot 2021-08-14 215349](https://user-images.githubusercontent.com/12575216/129450320-fd5ce048-c99b-4c0a-bf89-b6fd852592cf.png)
Logs
![Screenshot 2021-08-14 215414](https://user-images.githubusercontent.com/12575216/129450329-0de9814d-b3a5-4526-a145-04ea6b99cb42.png)

**Additional Context:**

If the RefindPlus folder is needed: [refind.zip](https://github.com/dakanji/RefindPlus/files/6986645/refind.zip)

**Comment by volcbs** [comment] 2021-08-14 14:56
Sorry, I just find the right time to post this issue.

**Comment by dakanji** [comment] 2021-08-14 18:42
Sorry but I can't reproduce your issue and in testing your RefindPlus folder, the feature works as it should.

There is an issue with PreviousBoot in v0.13.2.AG which has been dealt with in the current code base but this is not a factor in your case:
https://github.com/dakanji/RefindPlus/blob/1ea9bf44983caee2ee08cfb2457d7dbc7108a230/NEWS.txt#L6-L10

**Comment by volcbs** [comment] 2021-08-15 05:38
That's so weird then. It doesn't really work in my case, and I don't really do anything beside using that setup.

**Comment by dakanji** [comment] 2021-08-15 10:45
I revisited my test and the issue you describe does exist indeed.

Coincidentally, it has been fixed in the current code base by the changes made in the `Fixes Static 'PreviousBoot' Setup` I referred to earlier. It turns out it wasn't only tools that couldn't be changed.

You can build the current code base if you need the fix now.

**Closed** 2021-08-15 11:24 UTC
Labels: Known-Issue

**Comment by volcbs** [comment] 2021-08-17 10:54
Thanks for giving me the info. 
I'll wait until the next update since I'm not that in hurry atm.
